sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jwatkins12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jwatkins12/react-test npm test

after_success:
  - docker build -t jwatkins12/multi-client ./client
  - docker build -t jwatkins12/multi-nginx ./nginx
  - docker build -t jwatkins12/multi-server ./server
  - docker build -t jwatkins12/multi-worker ./worker
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jwatkins12/multi-client
  - docker push jwatkins12/multi-nginx
  - docker push jwatkins12/multi-server
  - docker push jwaktins12/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-615389170786"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
