sudo: required
services:
  - docker

before_install:
  - docker build -t jwatkins12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jwatkins12/react-test npm test

after_success:
  - docker build -t jwatkins12/multi-client ./client
  - docker build -t jwatkins12/multi-nginx ./nginx
  - docker build -t jwatkins12/multi-server ./server
  - docker build -t jwatkins12/multi-worker ./worker
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jwatkins12/multi-client
  - docker push jwatkins12/multi-nginx
  - docker push jwatkins12/multi-server
  - dokcerp ush jwaktins12/multi-worker
